name: Periodic tests
on:
  schedule:
    - cron: '0 0 * * 0'

defaults:
  run:
    shell: bash
env:
  PROJECT_NAME: fake-agent

jobs:
  run-tests:
    #uses: eclipse-volttron/github-tooling/.github/workflows/deploy-release.yml@main
    uses: schandrika/github-tooling/.github/workflows/run-tests.yml@periodic_test
