name: Periodic tests
on:
  schedule:
    - cron: '*/15 * * * *'

defaults:
  run:
    shell: bash
env:
  PROJECT_NAME: fake-agent

jobs:
  run-tests:
    #uses: eclipse-volttron/github-tooling/.github/workflows/deploy-release.yml@main
    if: ${{ github.ref == 'refs/heads/develop' }}
    uses: schandrika/github-tooling/.github/workflows/run-tests.yml@periodic_test
