ame: Test toml update

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash
env:
  PROJECT_NAME: fake-agent

jobs:
  update-toml:
    steps:
      - name: update toml file
        uses: schandrika/use-stable-volttron-releases@main