name: Test toml update

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash
env:
  PROJECT_NAME: fake-agent

jobs:
  update-toml:
    runs-on: ubuntu-22.04
    steps:
      - name: update toml file
        uses: schandrika/update_volttron_releases@main