name: Test with latest volttron

on:
  schedule:
    - cron: '0 0 * * 0'

defaults:
  run:
    shell: bash
env:
  PROJECT_NAME: fake-agent

jobs:
  test-with-latest-volttron:
    #uses: eclipse-volttron/github-tooling/.github/workflows/deploy-release.yml@main
    uses: schandrika/github-tooling/.github/workflows/test_with_latest_volttron.yml@test_with_latest